### ISSUE TITLE
Underscores not parsed as italics?

### ISSUE THREAD

**Issue by impinball** [whatwg/loader#10]
This just seemed weird to me, such as this in 2.2.1:

---

Algorithm steps that say

<pre><code>
1. RejectIfAbrupt(_x_).
</code></pre>

mean the same thing as:

<pre><code>
1. If _x_ is an abrupt completion, the return a promise rejected with _x_.[[value]].
1. Else if _x_ is a Completion Record, then let _x_ be _x_.[[value]].
</code></pre>

---

Shouldn't it look like this?

---

Algorithm steps that say

<pre><code>
1. RejectIfAbrupt(<i>x</i>).
</code></pre>

mean the same thing as:

<pre><code>
1. If <i>x</i> is an abrupt completion, the return a promise rejected with <i>x</i>.[[value]].
1. Else if <i>x</i> is a Completion Record, then let <i>x</i> be <i>x</i>.[[value]].
</code></pre>

---

This is throughout the spec, by the way.

**Comment by domenic** [comment]
The spec is using [Ecmarkdown](https://github.com/domenic/ecmarkdown) but currently it's more important to get the content right than to work through the technical issues involved in integrating Ecmarkdown with Bikeshed (the preprocessor currently being used).
