### ISSUE TITLE
3.1. Module Registry row [[State]] column description

### ISSUE THREAD

**Issue by johnjbarton** [whatwg/loader#11]
[[State]]	"fetch", "translate", "instantiate", "link", "ready"	The metadata object passed through the pipeline.

Maybe

[[State]]	"fetch", "translate", "instantiate", "link", "ready"	A constant set at the end of observable phases of loading indicating which phase this entry has completed.

**Comment by caridy** [comment]
@johnjbarton it is not the completed phase, but the current phase. Fixed on 1daa100a4ca5a39c636eddb27e1d1887f5778b7d.
