### ISSUE TITLE
[question] `Instantiation(loader, result, source)` will assume `result` is callable in step 3, but `result` is just an exotic namespace object that is not callable.

### ISSUE THREAD

**Issue by caridy** [whatwg/loader#115]
[loader.js](https://github.com/caridy/loader.js) implementation feedback

**Comment by caridy** [comment]
resolution: it could be a factory for back-compat with dynamic module systems.

action: it should test for callable or module registry, and act accordingly.

**Comment by caridy** [comment]
solves as part of refactor https://github.com/whatwg/loader/pull/122

![image](https://cloud.githubusercontent.com/assets/38969/12566138/eca38c94-c36c-11e5-9b97-c70db3fbff1c.png)

**Comment by guybedford** [comment]
Does this mean returning a factory in instantiate is no longer supported?

**Comment by caridy** [comment]
It is supported. Step 4 allows `optionalInstance` to be callable, then in https://whatwg.github.io/loader/#ensure-linked we guarantee that the factory is executed, and that it returns a namespace exotic object.

**Comment by guybedford** [comment]
Will read more carefully next time. Thanks for clarifying!
