### ISSUE TITLE
Provide / install

### ISSUE THREAD

**Issue by matthewp** [whatwg/loader#117]
I noticed these are missing now, is this a mistake?

**Comment by caridy** [comment]
* `install` is now [4.4.7. Registry.prototype.set(key, entry)](http://whatwg.github.io/loader/#registry-prototype-set) / [4.4.9. Registry.prototype.delete(key)](http://whatwg.github.io/loader/#registry-prototype-delete), which allow you to (synchronously) add and remove new entries into a registry.

* `provide` is now [5.4.8. ModuleStatus.prototype.resolve(stage, result)](http://whatwg.github.io/loader/#module-status-prototype-resolve) / [5.4.9. ModuleStatus.prototype.reject(stage, error)](http://whatwg.github.io/loader/#module-status-prototype-reject), which allow you to (using promise based values) resolve or reject a particular pending pipeline `stage` for a registry entry.

**Comment by matthewp** [comment]
Thanks.
