### ISSUE TITLE
Question: which objects will be exposed onto the window / global?

### ISSUE THREAD

**Issue by joeldenning** [whatwg/loader#125]
I know that `System.loader` is put onto the window / global, but don't know enough about reading through these specs to know if objects such as `Registry`, `ModuleStatus`, `Loader` will be exposed.

What is it in the spec that indicates which things are exposed onto the global and which ones aren't? At first, I thought it was potentially the difference between intrinsic objects (such as `%RegistryPrototype%`) and all the other objects (such as `Registry`), but now am not sure.

**Comment by caridy** [comment]
### Classes

ModuleStatus Class: `Reflect.Module.ModuleStatus`
  * https://whatwg.github.io/loader/#module-status-constructor

Loader Class: `Reflect.Loader`
  * https://whatwg.github.io/loader/#loader-constructor

Module Class: `Reflect.Module`
  * https://whatwg.github.io/loader/#module-constructor

Registry Class: this one will not be exposed.

### Instances

default loader instance: `System.loader`
  * https://whatwg.github.io/loader/#system-loader-instance

default loader's registry: `System.loader.registry`
  * https://whatwg.github.io/loader/#loader-registry

module status instances: any entry in `System.loader.registry`'s map.

Note: the spec for each constructor describes how to access that constructor in user-land, e.g.: 

> The Loader constructor is the %Loader% intrinsic object and the initial value of the Loader property of the the Reflect object. When called as a constructor it creates and initializes a new Loader object. When Loader is called as a function rather than as a constructor, it throws an exception.

Specifically, this part: _"the initial value of the Loader property of the the Reflect object"_

**Comment by joeldenning** [comment]
@caridy thanks that helps a lot.
