### ISSUE TITLE
Progress events

### ISSUE THREAD

**Issue by jhnns** [whatwg/loader#143]
Just wanted to know: Is there any intend to provide an API for some sort of progress event? Where the underlying implementation is able to inform the user about how many bytes have already been downloaded/still need to be downloaded.

Thanks in advance! 😀

**Comment by jhnns** [comment]
Original question: http://stackoverflow.com/questions/37787123/is-it-possible-to-let-webpacks-system-import-use-ajax-for-progress-events/37835802

**Comment by caridy** [comment]
No plans for such feature out-of-the-fox, but you can implement your own fetch hook to have more control over what you are fetching. Additionally, the metadata object will be exposed for each module status object (https://whatwg.github.io/loader/#module-status-internal-slots), which will give you some details if the fetching process is done by the default fetch hook, but that is not an event of any sort.

**Comment by Altiano** [comment]
Why shouldn't this not planned?
This is actually a good feature, right?
