### ISSUE TITLE
Per module-script tree information

### ISSUE THREAD

**Issue by Constellation** [whatwg/loader#148]
Looking through whatwg module spec and I think that the module-script assumes per-module-script-tree information. For example, `nonce` is propagated through the module script tree fetching.

However, in the current loader spec, it seems that BrowserLoader's `@@fetch` hook just takes the entry and the key. So the above information seems discarded through the pipeline. Is there any discussion to solve this?

Maybe, I misunderstand something. Please point it.

Personally, the easiest way to solve this issue is, instantiate `BrowserLoader` per script tag.
OR, passing metadata info throught the pipeline is one choise.

**Comment by caridy** [comment]
metadata was discussed here: https://github.com/whatwg/loader/issues/37, is that enough?

**Comment by Constellation** [comment]
Looks nice. We need to discuss it in #37.
