### ISSUE TITLE
Iterating over the registry

### ISSUE THREAD

**Issue by matthewp** [whatwg/loader#17]
In [this comment](https://github.com/whatwg/loader/issues/7#issuecomment-73353609) @dherman you mentioned that to share registries between loaders you could simply copy over the entries. I agree that this is a good natural way to share.  However to do that you would need to be able to iterate over the entries.  What do you think about having the Loader implement `@@iterator` so that this can be done?

**Comment by dherman** [comment]
Yes we will need a way to iterate. It's on my todo list. I'll leave this issue open till it's specified. Thanks!

**Comment by EisenbergEffect** [comment]
:+1:

**Comment by caridy** [comment]
Solved by https://github.com/whatwg/loader/pull/65.

```
for (let entry of System.loader.registry) {
    ...
})
```

**Comment by EisenbergEffect** [comment]
Excellent. Your work is appreciated :smile:

**Comment by matthewp** [comment]
Thanks @caridy !

**Comment by caridy** [comment]
https://whatwg.github.io/loader/#registry-prototype-@@iterator, while `GetRegistryEntry` defines what will be accesible thru the iteration.

_Note: since registry is not an iterator, it just implements `@@iterator`, you might get into racing conditions._
