### ISSUE TITLE
implement error state

### ISSUE THREAD

**Issue by dherman** [whatwg/loader#31]
- All error conditions need to set the \[[Error]] field.
- Implement the `.error()` method.
- Clear out the \[[Error]] field when installing.

**Comment by caridy** [comment]
Most of the work is now in as part of PR #97, the missing piece is the error propagation, I will work on that this week.

**Comment by caridy** [comment]
https://github.com/whatwg/loader/commit/215ca0e7d092d02503aa1520d2032f5b47f84997
