### ISSUE TITLE
4.2.3 5 RequestTranslate directly

### ISSUE THREAD

**Issue by guybedford** [whatwg/loader#32]
From the feedback previously:

* 4.2.3 5 Should RequestTranslate directly, don't need RequestFetch as it is implicit in RequestTranslate

The commit in https://github.com/whatwg/loader/commit/fe6090117e9837afcb72424b1b60446e9bca5c6b makes this valid again despite the previous revert.

//cc @caridy.

**Comment by caridy** [comment]
yes, that opens the door to remove that step. I'll send the PR today.

**Comment by caridy** [comment]
251c4fd2416c7818c246863aab46e28e20109e94
