### ISSUE TITLE
Specify the (lack of) constructor arguments.

### ISSUE THREAD

**Issue by johnjbarton** [whatwg/loader#33]
According to @guybedford on https://github.com/google/traceur-compiler/pull/1802, a Loader can be constructed with no arguments.  This constraint should be part of the spec so we can rely on it.

**Comment by caridy** [comment]
Solved by https://github.com/whatwg/loader/pull/65.

```
## Reflect.Loader()

When Reflect.Loader is called with no arguments, the following steps are taken:

...
```

**Comment by caridy** [comment]
https://whatwg.github.io/loader/#new-reflect-loader
