### ISSUE TITLE
Updated Feedback

### ISSUE THREAD

**Issue by guybedford** [whatwg/loader#40]
I've just updated our implementation to match the latest changes. Feedback below.
* 6.3.1 Should call requestInstantiateAll to ensure optimal loading (early dependency loading)
* 6.5.2. Reflect.Loader.install - we should probably throw here if `module` is not a module object.
* 4.1.6 Can call commitInstantiated when entry.[[Instantiate]] is undefined. Advisable to merge with 4.1.5 and just call fulfillInstantiate.
* It is possible to use the fulfillX functions at the end of each requestX function instead of repeating between the two: "Set entry.[[state]] to the max of entry.[[state]] and translate/fetch"
* 4.2.4 depEntry not defined when checking _depEntry_.[[State]], worth using a manual call to `ensureRegistered` at the top like all the others.
* 4.2.4 Circular references still don't have a stop condition here. Some type of extra state is needed, perhaps an `INSTANTIATE_ALL` that fits in after instantiate, which then gets marked as `LINK` within instantiateAll before hitting the circular references.

**Comment by caridy** [comment]
> 6.3.1 Should call requestInstantiateAll to ensure optimal loading (early dependency loading)

ok, will do.

> 6.5.2. Reflect.Loader.install - we should probably throw here if module is not a module object.

need more discussion. @dherman should look into this one. It is my understanding that `[[Module]]` could be undefined when installing it.

> 4.1.6 Can call commitInstantiated when entry.[[Instantiate]] is undefined. Advisable to merge with 4.1.5 and just call fulfillInstantiate.

cosmetic, we want to keep having all the fullfill* abstract operations to be called from public api methods (e.g.: loader.prototype.*). let's keep that separation.

> It is possible to use the fulfillX functions at the end of each requestX function instead of repeating between the two: "Set entry.[[state]] to the max of entry.[[state]] and translate/fetch"

same as above.

> 4.2.4 depEntry not defined when checking depEntry.[[State]], worth using a manual call to ensureRegistered at the top like all the others.

551d06abd9997c9bc845889e584d56fd4cede771


> 4.2.4 Circular references still don't have a stop condition here. Some type of extra state is needed, perhaps an INSTANTIATE_ALL that fits in after instantiate, which then gets marked as LINK within instantiateAll before hitting the circular references.

need more discussion. @dherman should look into this one.
