### ISSUE TITLE
Repeated calls to requestInstantiateAll, requestLink, requestReady

### ISSUE THREAD

**Issue by guybedford** [whatwg/loader#41]
`requestReady` is called on import, which in turn calls `requestLink` and `requestInstantiateAll`.

None of these store their promises if they have already been run, unlike all the other `requestX` calls.

So simultaneous imports can cause duplicated work:

```javascript
  System.import('a');
  System.import('a');
  System.import('a');
```

The above would trigger three calls to `requestReady`, `requestLink` and `requestInstantiateAll` for the same module, running all the logic in each one.

I haven't been able to create any conflict conditions, but I think it might be possible for these to occur. 

It may be worth storing the promises for these `requestReady`, `requestLink` and `requestInstantiateAll` functions on the entry just like all the other `requestX` functions?

**Comment by caridy** [comment]
solved by PR #97, it returns the same promise now.
