### ISSUE TITLE
Remote resource imports

### ISSUE THREAD

**Issue by brettz9** [whatwg/loader#43]
Does or will the spec support remote resource imports as in `System.import('http://example.com/remote.js')`, equivalent to dynamic script tag insertion (or if not, to say `eval(CORSResponse)` or `eval(SandboxedXHRResponse)`)?

**Comment by caridy** [comment]
Yes, it does support absolute and relative URLs. We will add more details in this section: https://whatwg.github.io/loader/#browser-resolve

**Comment by brettz9** [comment]
I see. Thanks!
