### ISSUE TITLE
5.1.1 HostResolveImportedModule somehow needs to find module's registry entry

### ISSUE THREAD

**Issue by ajklein** [whatwg/loader#45]
The current text says to look up the entry as a field of `module`, `[[RegistryEntry]]`. But this is the only reference to `[[RegistryEntry]]` in the whole spec. Presumably it needs to be lookup up in some loader's registry. But which loader?

I'm not at all sure of the right solution here, but the current text clearly doesn't work.

**Comment by ajklein** [comment]
Maybe the idea was to have 4.1.6 `CommitInstantiated` add a `[[RegistryEntry]]` backpointer from `instance` to `entry`?

**Comment by ajklein** [comment]
It would be great to get some feedback on this issue, as this is the critical place where the (now-final) ES spec and the loader spec interoperate, and it's currently completely busted.

**Comment by caridy** [comment]
@ajklein you're correct. Fixed in 2b6c61f19de859af485e49d946c6893675e0531b
