### ISSUE TITLE
4.1.7 Instantiation: ParseModule called with two arguments, only accepts one

### ISSUE THREAD

**Issue by ajklein** [whatwg/loader#46]
I think you can just leave off the `Realm` argument.

**Comment by caridy** [comment]
c159b5c5ec60f3e78e484c3f3f884061d0f5c6c3

**Comment by caridy** [comment]
the extra step to set `[[Realm]]` to the `loader.[[Realm]]` is not needed anymore, this is now fixed in 262, and `[[Realm]]` is set to the running execution context's Realm in ParseModule(): http://tc39.github.io/ecma262/#sec-parsemodule

**Comment by caridy** [comment]
I will create a new issue to track this change.

**Comment by domenic** [comment]
But see https://github.com/tc39/ecma262/pull/275 which tweaks this a little bit

**Comment by caridy** [comment]
ok, will track this issue here: https://github.com/whatwg/loader/issues/118
