### ISSUE TITLE
Loader.install should resolve pending imports

### ISSUE THREAD

**Issue by matthewp** [whatwg/loader#48]
This was a bug in the old spec and appears to still be present. Consider this code:

```js
loader.import("main.js");

setTimeout(function(){
  loader.install("main.js", value);
}, 5);
```

This creates a race condition where if `main.js` passes through `resolve` before `loader.install` is called it will continue through the loading steps and (I believe) fail an assertion in linking.

Is `loader.cancel` intended to fix this issue?

**Comment by matthewp** [comment]
@caridy I think this should be labeled a bug. This probably means `loader.install` and `loader.provide` can only be safely used prior to any `<module>` tags or any module loading having started.

This same bug existed in the old System.set/System.define form and it make them effectively unusable.

**Comment by caridy** [comment]
I will look into the details next week.

**Comment by dherman** [comment]
This may have been fixed along the way as @caridy has been cleaning up the pipeline logic. He's currently working on a refactor of how the pipeline is represented (see PR #91). The semantics should be carefully ensuring there's only ever one promise stored for each stage, and we should only ever cancel an earlier stage's promise after a later stage has already been resolved. So I don't see off the top of my head how this bug would come up. But let's revisit it after the PR lands.

**Comment by caridy** [comment]
@matthewp this is no fixed (after PR #97).

**Comment by matthewp** [comment]
You meant "now fixed", right?

**Comment by caridy** [comment]
jejeje, yes! fixed.
