### ISSUE TITLE
Issues in RequestInstantiate / RequestInstantiateAll

### ISSUE THREAD

**Issue by jonco3** [whatwg/loader#49]
Currently RequestInstantiate() calls both RequestFetch() and RequestTranslate(), which itself calls RequestFetch().  It looks like it should just call the RequestTranslate().

Also RequestInstantiateAll() refers to _depEntry_ which is not defined anywhere.

**Comment by caridy** [comment]
this is a partial duplicated of https://github.com/whatwg/loader/issues/32

**Comment by caridy** [comment]
fixed in 251c4fd2416c7818c246863aab46e28e20109e94 and 551d06abd9997c9bc845889e584d56fd4cede771
