### ISSUE TITLE
6.7.1.2. Reflective Module.ResolveExport() - Review SyntaxError on circular dependencies

### ISSUE THREAD

**Issue by caridy** [whatwg/loader#55]
Reported by @bmeck (https://github.com/WebAssembly/design/issues/256#issuecomment-120558466)

**Comment by guybedford** [comment]
I believe this refers to circular references in the bindings setup. The point is I can't do:

a.js
```javascript
export {a} from './b.js';
```
b.js
```javascript
export {a} from './a.js';
```

So we stop circularity of bindings, not circularity of modules.

**Comment by dherman** [comment]
@guybedford is right: this part of the semantics treats re-export cycles as a static error, not cyclic module dependencies. Re-export cycles are nonsense: in the example above, `a` is not actually defined anywhere.
