### ISSUE TITLE
Reflect.Loader.import is not a valid method name

### ISSUE THREAD

**Issue by jonco3** [whatwg/loader#60]
Since "import" is a keyword in ES6.

**Comment by teppeis** [comment]
It's valid. A reserved word is an IdentifierName, so it can be used as a property name.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_word_usage

**Comment by MajorBreakfast** [comment]
It's called `System.import()` today and works ;)

**Comment by jonco3** [comment]
Thanks teppeis, so it's not valid as an Identifier but it is valid as a PropertyName.
