### ISSUE TITLE
2.3.2 SimpleDefine spec error

### ISSUE THREAD

**Issue by FUDCo** [whatwg/loader#61]
Section 2.3.2 SimpleDefine, step 2 says:
   Return the result of calling OrdinaryDefineOwnProperty(obj, name, value).
If I'm reading things right, that should be:
   Return the result of calling OrdinaryDefineOwnProperty(obj, name, desc).

**Comment by caridy** [comment]
@FUDCo thanks for spotting this problem. keep them coming ;)
