### ISSUE TITLE
Loader implementation

### ISSUE THREAD

**Issue by monolithed** [whatwg/loader#63]
Are there any implementation?

**Comment by caridy** [comment]
there are some polyfills out there [1], but this specification is a living doc and it is subject to changes in the upcoming weeks.

* https://github.com/ModuleLoader/es6-module-loader
* https://github.com/caridy/es6-micro-loader

**Comment by matthewp** [comment]
Note that none of the polyfills reflect the current APIs, es6ml in particular is a blend of this spec with an older spec that was part of es6 back a year ago. The APIs are still being defined so (my guess) it will be a while before it is in a place where a stable polyfill can be made (correct me if I'm misspeaking here @caridy ).

**Comment by monolithed** [comment]
> there are some polyfills out there

But
> none of the polyfills reflect the current APIs

For example, there's no such thing as a `Reflect.Loader`
And I don't understand who should implement this standard (what his future).

**Comment by caridy** [comment]
Ok, let me try to give you a tagline here: there will be a polyfill once we settle on the API described in this specification.

**Comment by monolithed** [comment]
I got it. 
What about possible conflicts with ES and are there any plan about ES2016?

**Comment by probins** [comment]
for background, see, for example, https://code.google.com/p/v8/issues/detail?id=1569#c29 for implementation status in V8/Chromium/Chrome

**Comment by monolithed** [comment]
@probins, thanks for the link!

**Comment by caridy** [comment]
https://github.com/whatwg/loader#implementation-status

**Comment by guybedford** [comment]
@caridy and also https://bugzilla.mozilla.org/show_bug.cgi?id=568953.
