### ISSUE TITLE
Reserved module names

### ISSUE THREAD

**Issue by matthewbauer** [whatwg/loader#64]
Would it be reasonable to reserve certain module names? For example, anything starting with an "@" would be reserved for the loader to define.

The main use I'm thinking of would be an "@window" module as an alias for the global "window" object used in web browsers. This would be helpful for porting over code that depends on things being in the global object that may or may not be there depending on the execution environment.

As an example for base64 encoding:

```js
import {btoa, atob} from "@window";
atob(btoa("asdf")) === "asdf";
```

In a web browser, the loader would just resolve these to window.btoa and window.atob. In Node, however, the loader could resolve this to a polyfill.

This might not be necessary in the spec but it is something that should be resolved as Node and web environments move closer together.

**Comment by matthewp** [comment]
There's no longer a concept of module names in the spec.  This means you can't do `loader.lookup("jquery")` and get jquery, but rather you have to do `loader.lookup("http://example.com/jquery.js")`.

I think what you are proposing is that the module identifier "@window" be converted to a namespace uri, maybe something like `system://@window`.

I don't think there should be any *reserved* names. That goes against the spirit of JavaScript, you can override anything. **Default** names, on the other hand, are a great idea.

But the correct way to implement this is to have them be on the `sites` table by default. That way if I want to override "@window", I can just override it on the sites table.  This is important for testing, I want to be able to mock the window and doing that with loader config is a great way to do it.

On another note, I don't like the "@" prefix, I think it's weird. I don't have a better solution, but I think there should be a common namespace of some kind, like maybe "system/window".  This way there aren't a thousand of these default names.

**Comment by matthewbauer** [comment]
Okay that makes sense.

The main thing I'm concerned with is that it's relatively easy to move Node stuff to the web because most of the builtins are already modular. On the other hand, web builtins are all put into the global object. I suppose this might not really make sense in the loader spec. But, in the end, I think it will really improve in the JavaScript ecosystem if there is a way to say "I need this window function" without having to look through global definitions and provide a fallback.

**Comment by matthewp** [comment]
Yes, this is definitely a worthy issue. Eventually everything should be imported, including the loader itself (actually this one is very important), deciding what the names should be is open to debate though.

**Comment by caridy** [comment]
The `ModuleSpecifier` can be anything, and understanding its meaning to resolve a module is something that belongs to the user-land. Browser's default loader will implement a simple logic, but the rest is all up to users of the loader. With the time, patterns will emerge, and we can try to improve from there. There are other things like built-in modules, which most likely will be the way JS will evolve in the future IMO, something like `import {bigNumber} from "math"`, but that will take a while to shape.

@matthewbauer can we close this issue?
