### ISSUE TITLE
Introducing the new state, "ResolveDependencies"

### ISSUE THREAD

**Issue by Constellation** [whatwg/loader#68]
I think that the current draft spec incurs infinite recursion when there is the circular dependencies.
The situation is the following,

There are several modules,

__A__: This is the entry point.
```js
import "B"
```

__B__
```js
import "C"
```

__C__
```js
import "B"
```

1. At that time, before linking the modules, we call `RequestInstantiateAll(A)`.
2. In `RequestInstantiateAll(A)`, step 1-b-i-1, we extract the B dependency.
3. So, step 1-b-i-3, we perform `RequestInstantiateAll(B)`.
4. Later, it will extract the C dependency. So, step 1-b-i-3 in `RequestInstantiateAll(B)`, we call `RequestInstantiateAll(C)`.
5. Since C has the B dependency, in `RequestInstantiateAll(C)` step 1-b-i-3, we again call `RequestInstantiateAll(B)`.
6. Here, now, since once `RequestInstantiate(B)` is called inside `RequestInstantiateAll(B)`, it immediately returns the promise `B.[[Instantiate]]`. But, Now, __we stored the status of instantiation in [[Instantiate]], but we didn't store the status of collecting the dependencies__.
7. So, in `RequestInstantiateAll(B)`, `RequestInstantiate(B)` returns the stored promise, but __it performs the dependency resolution again in 1-a or later__. So it will call `RequestInstantiateAll(C)` at step 1-b-i-3 again.
8. `RequestInstantiateAll(B)` and `RequestInstantiateAll(C)` are called repeatedly.

This problem comes from that the current algorithm does not store the status of "resolving the dependencies".

To solve this, I would like to propose introducing the new state `ResolveDependencies`. That means, "Now, the instantiation is done, so the  entry is ready to resolve the dependencies. And if there's entry.[[ResolveDependencies]] promise and the state is `ResolveDependencies`, we're resolving the dependency of the module just now".

The algorithm becomes the following,

### CommitInstantiated(loader, key)
1. Let _instance_ be Instantiation(_loader_, _optionalInstance_, _source_).
1. ReturnIfAbrupt(_instance_).
1. // TODO: edge case: what if _instance_ is a thenable function?
1. Fulfill _entry_.[[Instantiate]] with _instance_.
1. Let _deps_ be a new empty List.
1. If _instance_ is a Module Record, then:
  1. Assert: _instance_ is a Source Text Module Record.
  1. Set _instance_.[[RegistryEntry]] to _entry_.
  1. For each _dep_ in _instance_.[[RequestedModules]], do:
    1. Append the record { [[key]]: _dep_, [[value]]: *undefined* } to _deps_.
1. Set _entry_.[[Dependencies]] to _deps_.
1. Set _entry_.[[Module]] to _instance_.
1. SetStateToMax(_entry_, __"resolveDependencies"__).

### RequestResolveDependencies(loader, key)

1. Let _entry_ be EnsureRegistered(_loader_, _key_).
2. Let _linkStateValue_ be GetStateValue("link").
3. If _stateValue_ is greater than _linkStateValue_, return a new error promise.
3. If _entry_.[[ResolveDependencies]] is not *undefined*, return _entry_.[[ResolveDependencies]].
4. Return the result of transforming RequestInstantiate(_loader_, _key_) with a fulfillment handler that, when called with argument _entry_, runs the following steps:
    1. Let _depLoads_ be a new empty List.
    2. For each _pair_ in _entry_.[[Dependencies]], do:
        1. Let _p_ be the result of transforming Resolve(_loader_, _pair_.[[key]], _key_) with a fulfillment handler that, when called with value _depKey_, runs the following steps:
            1. Let _depEntry_ be EnsureRegistered(_loader_, _depKey_).
            1. If _depEntry_.[[ResolveDependencies]] is not *undefined*
                1. Return the result of transforming _depEntry_.[[Instantiate]] with a fulfillment handler that, when called with value _depEntry_, runs the following steps:
                    1. Let _dep_ be _depEntry_.[[Module]].
                    1. Set _pair_.[[value]] to _dep_.
                    1. Return _depEntry_.
            1.  Return the result of transforming RequestCollect(_loader_, _depKey_) with a fulfillment handler that, when called with value _depEntry_, runs the following steps:
                1. Let _dep_ be _depEntry_.[[Module]].
                1. Set _pair_.[[value]] to _dep_.
                1. Return _depEntry_.
        1. Append _p_ to _depLoads_.
    1. Let _p_ be the result of waiting for all _depLoads_.
    1. Return the result of transforming _p_ with a fulfillment handler that, when called, runs the following steps:
        1. SetStateToMax(_entry_, "link").
        1. Return _entry_.

**Comment by caridy** [comment]
hey @Constellation, happy to see you guys digging around here ;).

I will review this asap.

**Comment by Constellation** [comment]
@caridy Thank you. We're now prototyping the loader implementation in WebKit. So I think we can help your spec. (And your spec already helps us a lot :D)

**Comment by Constellation** [comment]
After implementing this part in the prototype in WebKit, we slightly modified the proposal and its name.
I've reflected it.

**Comment by caridy** [comment]
most likely related to https://github.com/whatwg/loader/issues/79

**Comment by guybedford** [comment]
I do think a new state is needed here, it's about distinguishing between _instantiate_ (just this module) and _instantiate all_ (this module and all its dependencies) as two separate states before _link_.

**Comment by guybedford** [comment]
Note this resolves the last issue in https://github.com/whatwg/loader/issues/40.

**Comment by caridy** [comment]
we were unable to get to this issue yesterday, we were stuck on the promise issues, but we will try to think through this issue early next week. stay tuned.

**Comment by Constellation** [comment]
How about this? @caridy @domenic

**Comment by caridy** [comment]
sorry for the delay on this, will try to get dave and yehuda to discuss it next week. Btw, @dherman already spent some time on this few weeks ago, we haven't get to conclusion yet.

**Comment by dherman** [comment]
@Constellation — I just want to thank you for your contribution here. I've gone ahead and specified essentially the same algorithm (but with different names) in 261543c66c235b2a4b3a9e5076b6dd0386a94ec3.

**Comment by Constellation** [comment]
@dherman: :-)
