### ISSUE TITLE
Implementation status seems out of date

### ISSUE THREAD

**Issue by matthewrobb** [whatwg/loader#71]
The implementation status section states that progress is blocked by implementors implementing module support but looking into it further you find stuff like [this](https://code.google.com/p/v8/issues/detail?id=1569#c29).

>This work is currently blocked on the completion of a specification for the Module Loader, which is being worked on in the WHATWG: https://github.com/whatwg/loader
>
>What's currently implemented in V8 is parsing, which is most of what is specified in ES2015 (the loader is left out of that spec).

**Comment by caridy** [comment]
@matthewrobb we have been working to unblock @ajklein and his team. The purpose of the status info is just to knowledge that we have certain traction among implementers, but a lot to be done still.
