### ISSUE TITLE
Regarding "Implementation status" section in README.md - deadlock detected?

### ISSUE THREAD

**Issue by TimeForAChange** [whatwg/loader#92]
Simply judging by the README.md and comments 36,... and especially [reply nr. 39](https://code.google.com/p/v8/issues/detail?id=1569#c39) on a ticket for V8 there seems to be deadlock because teams are waiting for each other?

https://code.google.com/p/v8/issues/detail?id=1569#c36

**Comment by matthewp** [comment]
Read the commit log and issues here, there is progress being made. I don't know why the readme says that about ES2015 modules needing to be implemented first.

**Comment by TimeForAChange** [comment]
Consider this a ticket about the README, not actually a question.

**Comment by caridy** [comment]
Loader and Modules are not the same thing :), the progress noted in README is about modules, which is what we have spec'd "already". We can probably be more clear about that... here is the roadmap: https://github.com/whatwg/loader/blob/master/roadmap.md

**Comment by TimeForAChange** [comment]
@caridy I have no idea why you thought you needed to say they are not the same thing. It's like saying water is wet when the talk is about who should pick up the children? True - but unrelated. Sorry to have to say.

**Comment by caridy** [comment]
@TimeForAChange I don't think we are arguing here.

I have updated the readme to reflect the current state of the affair, based on the roadmap.
