### ISSUE TITLE
GetRegistryEntry defines name 'result' twice

### ISSUE THREAD

**Issue by jonco3** [whatwg/loader#98]
https://whatwg.github.io/loader/#registry-GetRegistryEntry

> Let result be the result of transforming currentStage\.\[\[Result\]\] with a new pass\-through promise\.
> Let stage be currentStage\.\[\[Stage\]\]\.
> Let result be CreateObject\(\)\.

Result is defined twice here which makes subsequent use ambiguous.

**Comment by caridy** [comment]
this is not longer the case after the refactor from PR #96

**Comment by caridy** [comment]
fixed by PR #97, we no longer have `GetRegistryEntry`.

**Comment by jonco3** [comment]
Great, thanks.
